//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_SmartVidéo.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilmDTO", Namespace="http://schemas.datacontract.org/2004/07/FilmDTOLibrary")]
    [System.SerializableAttribute()]
    public partial class FilmDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web_SmartVidéo.ServiceReference1.ActeurDTO[] ActeurlistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web_SmartVidéo.ServiceReference1.GenreDTO[] GenrelistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Original_titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosterpathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web_SmartVidéo.ServiceReference1.RealisateurDTO[] RealisateurlistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RuntimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrailerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web_SmartVidéo.ServiceReference1.ActeurDTO[] Acteurlist {
            get {
                return this.ActeurlistField;
            }
            set {
                if ((object.ReferenceEquals(this.ActeurlistField, value) != true)) {
                    this.ActeurlistField = value;
                    this.RaisePropertyChanged("Acteurlist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web_SmartVidéo.ServiceReference1.GenreDTO[] Genrelist {
            get {
                return this.GenrelistField;
            }
            set {
                if ((object.ReferenceEquals(this.GenrelistField, value) != true)) {
                    this.GenrelistField = value;
                    this.RaisePropertyChanged("Genrelist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Original_title {
            get {
                return this.Original_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.Original_titleField, value) != true)) {
                    this.Original_titleField = value;
                    this.RaisePropertyChanged("Original_title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Posterpath {
            get {
                return this.PosterpathField;
            }
            set {
                if ((object.ReferenceEquals(this.PosterpathField, value) != true)) {
                    this.PosterpathField = value;
                    this.RaisePropertyChanged("Posterpath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web_SmartVidéo.ServiceReference1.RealisateurDTO[] Realisateurlist {
            get {
                return this.RealisateurlistField;
            }
            set {
                if ((object.ReferenceEquals(this.RealisateurlistField, value) != true)) {
                    this.RealisateurlistField = value;
                    this.RaisePropertyChanged("Realisateurlist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Runtime {
            get {
                return this.RuntimeField;
            }
            set {
                if ((this.RuntimeField.Equals(value) != true)) {
                    this.RuntimeField = value;
                    this.RaisePropertyChanged("Runtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Trailer {
            get {
                return this.TrailerField;
            }
            set {
                if ((object.ReferenceEquals(this.TrailerField, value) != true)) {
                    this.TrailerField = value;
                    this.RaisePropertyChanged("Trailer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActeurDTO", Namespace="http://schemas.datacontract.org/2004/07/FilmDTOLibrary")]
    [System.SerializableAttribute()]
    public partial class ActeurDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CharacterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Character {
            get {
                return this.CharacterField;
            }
            set {
                if ((object.ReferenceEquals(this.CharacterField, value) != true)) {
                    this.CharacterField = value;
                    this.RaisePropertyChanged("Character");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenreDTO", Namespace="http://schemas.datacontract.org/2004/07/FilmDTOLibrary")]
    [System.SerializableAttribute()]
    public partial class GenreDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RealisateurDTO", Namespace="http://schemas.datacontract.org/2004/07/FilmDTOLibrary")]
    [System.SerializableAttribute()]
    public partial class RealisateurDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UtilisateursDTO", Namespace="http://schemas.datacontract.org/2004/07/SmartVideoDBDTO")]
    [System.SerializableAttribute()]
    public partial class UtilisateursDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PseudoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Carte {
            get {
                return this.CarteField;
            }
            set {
                if ((object.ReferenceEquals(this.CarteField, value) != true)) {
                    this.CarteField = value;
                    this.RaisePropertyChanged("Carte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pseudo {
            get {
                return this.PseudoField;
            }
            set {
                if ((object.ReferenceEquals(this.PseudoField, value) != true)) {
                    this.PseudoField = value;
                    this.RaisePropertyChanged("Pseudo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFilms", ReplyAction="http://tempuri.org/IService1/GetFilmsResponse")]
        Web_SmartVidéo.ServiceReference1.FilmDTO[] GetFilms(int debut, int nb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFilms", ReplyAction="http://tempuri.org/IService1/GetFilmsResponse")]
        System.Threading.Tasks.Task<Web_SmartVidéo.ServiceReference1.FilmDTO[]> GetFilmsAsync(int debut, int nb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGenreWithId", ReplyAction="http://tempuri.org/IService1/GetGenreWithIdResponse")]
        Web_SmartVidéo.ServiceReference1.GenreDTO[] GetGenreWithId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGenreWithId", ReplyAction="http://tempuri.org/IService1/GetGenreWithIdResponse")]
        System.Threading.Tasks.Task<Web_SmartVidéo.ServiceReference1.GenreDTO[]> GetGenreWithIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetActorWithId", ReplyAction="http://tempuri.org/IService1/GetActorWithIdResponse")]
        Web_SmartVidéo.ServiceReference1.ActeurDTO[] GetActorWithId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetActorWithId", ReplyAction="http://tempuri.org/IService1/GetActorWithIdResponse")]
        System.Threading.Tasks.Task<Web_SmartVidéo.ServiceReference1.ActeurDTO[]> GetActorWithIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDirectorWithId", ReplyAction="http://tempuri.org/IService1/GetDirectorWithIdResponse")]
        Web_SmartVidéo.ServiceReference1.RealisateurDTO[] GetDirectorWithId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDirectorWithId", ReplyAction="http://tempuri.org/IService1/GetDirectorWithIdResponse")]
        System.Threading.Tasks.Task<Web_SmartVidéo.ServiceReference1.RealisateurDTO[]> GetDirectorWithIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFilmWithId", ReplyAction="http://tempuri.org/IService1/GetFilmWithIdResponse")]
        Web_SmartVidéo.ServiceReference1.FilmDTO[] GetFilmWithId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFilmWithId", ReplyAction="http://tempuri.org/IService1/GetFilmWithIdResponse")]
        System.Threading.Tasks.Task<Web_SmartVidéo.ServiceReference1.FilmDTO[]> GetFilmWithIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetTrailer", ReplyAction="http://tempuri.org/IService1/SetTrailerResponse")]
        void SetTrailer(int id, string trailer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetTrailer", ReplyAction="http://tempuri.org/IService1/SetTrailerResponse")]
        System.Threading.Tasks.Task SetTrailerAsync(int id, string trailer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        string Login(string E, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string E, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/findUser", ReplyAction="http://tempuri.org/IService1/findUserResponse")]
        Web_SmartVidéo.ServiceReference1.UtilisateursDTO findUser(string E);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/findUser", ReplyAction="http://tempuri.org/IService1/findUserResponse")]
        System.Threading.Tasks.Task<Web_SmartVidéo.ServiceReference1.UtilisateursDTO> findUserAsync(string E);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update", ReplyAction="http://tempuri.org/IService1/UpdateResponse")]
        void Update(Web_SmartVidéo.ServiceReference1.UtilisateursDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update", ReplyAction="http://tempuri.org/IService1/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(Web_SmartVidéo.ServiceReference1.UtilisateursDTO user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Web_SmartVidéo.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Web_SmartVidéo.ServiceReference1.IService1>, Web_SmartVidéo.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Web_SmartVidéo.ServiceReference1.FilmDTO[] GetFilms(int debut, int nb) {
            return base.Channel.GetFilms(debut, nb);
        }
        
        public System.Threading.Tasks.Task<Web_SmartVidéo.ServiceReference1.FilmDTO[]> GetFilmsAsync(int debut, int nb) {
            return base.Channel.GetFilmsAsync(debut, nb);
        }
        
        public Web_SmartVidéo.ServiceReference1.GenreDTO[] GetGenreWithId(int id) {
            return base.Channel.GetGenreWithId(id);
        }
        
        public System.Threading.Tasks.Task<Web_SmartVidéo.ServiceReference1.GenreDTO[]> GetGenreWithIdAsync(int id) {
            return base.Channel.GetGenreWithIdAsync(id);
        }
        
        public Web_SmartVidéo.ServiceReference1.ActeurDTO[] GetActorWithId(int id) {
            return base.Channel.GetActorWithId(id);
        }
        
        public System.Threading.Tasks.Task<Web_SmartVidéo.ServiceReference1.ActeurDTO[]> GetActorWithIdAsync(int id) {
            return base.Channel.GetActorWithIdAsync(id);
        }
        
        public Web_SmartVidéo.ServiceReference1.RealisateurDTO[] GetDirectorWithId(int id) {
            return base.Channel.GetDirectorWithId(id);
        }
        
        public System.Threading.Tasks.Task<Web_SmartVidéo.ServiceReference1.RealisateurDTO[]> GetDirectorWithIdAsync(int id) {
            return base.Channel.GetDirectorWithIdAsync(id);
        }
        
        public Web_SmartVidéo.ServiceReference1.FilmDTO[] GetFilmWithId(int id) {
            return base.Channel.GetFilmWithId(id);
        }
        
        public System.Threading.Tasks.Task<Web_SmartVidéo.ServiceReference1.FilmDTO[]> GetFilmWithIdAsync(int id) {
            return base.Channel.GetFilmWithIdAsync(id);
        }
        
        public void SetTrailer(int id, string trailer) {
            base.Channel.SetTrailer(id, trailer);
        }
        
        public System.Threading.Tasks.Task SetTrailerAsync(int id, string trailer) {
            return base.Channel.SetTrailerAsync(id, trailer);
        }
        
        public string Login(string E, string pass) {
            return base.Channel.Login(E, pass);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string E, string pass) {
            return base.Channel.LoginAsync(E, pass);
        }
        
        public Web_SmartVidéo.ServiceReference1.UtilisateursDTO findUser(string E) {
            return base.Channel.findUser(E);
        }
        
        public System.Threading.Tasks.Task<Web_SmartVidéo.ServiceReference1.UtilisateursDTO> findUserAsync(string E) {
            return base.Channel.findUserAsync(E);
        }
        
        public void Update(Web_SmartVidéo.ServiceReference1.UtilisateursDTO user) {
            base.Channel.Update(user);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(Web_SmartVidéo.ServiceReference1.UtilisateursDTO user) {
            return base.Channel.UpdateAsync(user);
        }
    }
}
